version: '2'

services:
    db:
        image: mariadb
        container_name: db_tour
        command: mysqld --innodb-buffer-pool-size=20M
        volumes:
            - "/var/lib/mysql:/var/lib/mysql"
        environment:
            - "MYSQL_DATABASE=db_tour"
            - "MYSQL_USER=tour_user"
            - "MYSQL_PASSWORD=tour_user_pwd"
            #- "MYSQL_ROOT_PASSWORD=root_passwd"
        ports:
            - "3306:3306"
        restart: always
        networks:
            - code-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - db
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 8080:80
        volumes:
            - /sessions
        networks:
            - code-network
    app:
        build: config/docker
        container_name: app_tour
        depends_on:
            - db
        restart: always
        expose:
            - "9000"
        volumes:
            - ./:/var/www
            - ./runtime/logs/xdebug/:/tmp/xdebug_log
        environment:
            XDEBUG_CONFIG: remote_host=192.168.32.1
        networks:
            - code-network
    nginx:
        image: nginx:latest
        container_name: nginx_tour
        restart: always
        ports:
            - "80:80"
            - "4443:443"
        links:
            - app
        volumes:
            - ./:/var/www
            - ./config/nginx/app.conf:/etc/nginx/conf.d/app.conf
        networks:
            - code-network
networks:
    code-network:
        driver: bridge